import "./globals.css";
import { Roboto } from "next/font/google";
import Navbars from "./components/layout/Navbars";
import Footers from "./components/layout/Footers";
import Header from "./components/layout/Header";
const roboto = Roboto({ weight: "400", subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full mx-4 md:mx-16 scroll-smooth">
      <body className={roboto.className}>
        <Header>{children}</Header>
      </body>
    </html>
  );
}
